Alumni_Portal/Alumni_Portal/urls.py
from django.contrib import admin
from django.urls import path, include
from alumni_app import views

urlpatterns = [
    path('', include('alumni_app.urls')),
    path('admin/', admin.site.urls),



]

Alumni_Portal/alumni_app/urls.py
from django.contrib import admin
from django.urls import path
from alumni_app import views

urlpatterns = [
  path('', views.home, name='home'),
  # TEMPORARY
  path('signin', views.sign_in, name='signin'),
  path('signout', views.home, name='signout'),
  path('calendar', views.home, name='calendar'),
  path('callback', views.callback, name='callback'),

]

Alumni_Portal/alumni_response/urls.py
from django.contrib import admin
from django.urls import path, re_path ,include
from . import views

app_name='alumni_response'

urlpatterns=[
    path('form1/',views.response1,name='form1'),
    re_path(r'^form2a/(?P<pk>\d+)/$',views.response2a,name='form2a'),
    re_path(r'^form2b/(?P<pk>\d+)/$',views.response2b,name='form2b'),
    re_path(r'^form2c/(?P<pk>\d+)/$',views.response2c,name='form2c'),
    re_path(r'^form3/(?P<pk>\d+)/$',views.response3,name='form3'),
    re_path(r'^detail/(?P<pk>\d+)/$', views.AlumniDetail.as_view(template_name='alumni_response/alum_detail.html'),name='alumni_detail'),
    re_path(r'^form_update/(?P<pk>\d+)/$', views.update_current, name='form_update'),

]

Alumni_Portal/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List of Alumni:</h1>
    <table>
      <thead>
        <th>
          <h3>Name</h3>
        </th>
        <th>
          <h3>Branch</h3>
        </th>
        <th>
          <h3>Current Position</h3>
        </th>
        <th>
          <h3>After 4th Year</h3>
        </th>
        <th>
          <h3>Job Profile</h3>
        </th>
        <th>
          <h3>Company</h3>
        </th>
        <th>
          <h3>Higher Study Programme</h3>
        </th>
        <th>
          <h3>University</h3>
        </th>
        <th>
          <h3>Start_Up Name</h3>
        </th>
      </thead>
      {% for response in response %}
      <a href="{% url 'alumni_response:alumni_detail' pk=response.pk %}">
        <tr>
          <td><a href="{% url 'alumni_response:alumni_detail' pk=response.pk %}">{{response.alumni}}</a></td>
          <td>{{response.department}}</td>
          <td>{{response.current_job}}</td>
          <td>{{response.post_college}}</td>
          {% if response.post_college == 'Higher studies' %}
          <td>NA</td>
          <td>NA</td>
          <td>{{response.higher.programme}}</td>
          <td>{{response.higher.university}}</td>
          <td>NA</td>
          {% elif response.post_college == 'Job' %}
          <td>response.job.profile</td>
          <td>response.job.company</td>
          <td>NA</td>
          <td>NA</td>
          <td>NA</td>
          {% elif response.post_college == 'Entrepreneurship' %}
          <td>NA</td>
          <td>NA</td>
          <td>NA</td>
          <td>NA</td>
          <td>response.start_up.startup_name</td>
          {% endif %}
        </tr>
      </a>

      {% endfor %}
    </table>
  </body>
</html>